### ISSUE TITLE
Simpler implementation

### ISSUE THREAD

**Issue by mathiasbynens** [guybedford/proposal-is-usv-string#1]
Thanks for putting together this proposal.

There’s value in writing out the algorithm like in https://github.com/guybedford/proposal-is-usv-string#algorithm. For polyfilling/shimming purposes however, simpler implementations are possible, e.g.

```js
function isWellFormed(string) {
  const reLoneSurrogate = /\p{Surrogate}/u;
  return !reLoneSurrogate.test(string);
}
```

Would it make sense to mention this in the README as well?

**Comment by guybedford** [comment]
We could certainly call out other userland methods here eg to inform polyfilling. Although the above regex won't catch the "out of band" surrogates like `"\ud000"` or `"\uf800"` I think?

**Comment by guybedford** [comment]
Sorry `\ud000` is valid of course, I mean `\uf800` and related in `(D800, FC00]` range specifically.

**Comment by mathiasbynens** [comment]
The regex matches all lone surrogates, i.e. the entire range from U+D800 to U+DFFF. I'm not sure what you mean w.r.t. U+F800 — that's not a surrogate.

**Comment by guybedford** [comment]
The validation of whether a string is a valid USV string requires also validating there are no "invalid surrogates" in that range.

**Comment by mathiasbynens** [comment]
Sorry, I still don't follow. What makes you say that? U+F800 and U+FC00 are perfectly valid [Unicode scalar values](https://www.unicode.org/glossary/#unicode_scalar_value).

**Comment by guybedford** [comment]
Ahh right my mistake, thank you for correcting me on this! In that case my example algorithm needs to be updated to match the regex. Will do both updates in one shortly.

**Comment by guybedford** [comment]
Hmm, actually I'm still not sure about this.... The link there described unicode scalar values as:

> In other words, the ranges of integers 0 to D7FF and E000 to 10FFFF inclusive

This clearly omits D850 etc.

**Comment by mathiasbynens** [comment]
> Hmm, actually I'm still not sure about this.... The link there described unicode scalar values as:
> 
> > In other words, the ranges of integers 0 to D7FF and E000 to 10FFFF inclusive
> 
> This clearly omits D850 etc.

It does. What are you unsure about?

- Surrogates are U+D800 to U+DFFF.
- Scalar values are the set of non-surrogates in the range U+0000 to U+10FFFF, i.e. U+0000 to U+D7FF + U+E000 to U+10FFFF.

**Comment by guybedford** [comment]
Ahh ok my confusion here was in my initial testing of the regex I missed that `\p{Surrogate}` does in fact match the D800 - DFFF range which I assumed because of the naming would only match actual valid surrogates and not invalid surrogates.

In that case I think we're arguing around the same point!

**Comment by mathiasbynens** [comment]
The `u` flag ensures only whole code points are matched, so surrogates that are part of a pair are not matched separately.
